In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings("ignore")

In [2]:
data=pd.DataFrame(columns=["CODE_COLLEGE","COLLAGE_NAME"])

In [3]:
df=pd.read_csv("csv_preprocessing_2.csv")

In [4]:
df_co=df.copy()

In [5]:
df_co

ID                                           Colleges  \
0   E001  University of Visvesvaraya College of Engineering   
1   E001  University of Visvesvaraya College of Engineering   
2   E001  University of Visvesvaraya College of Engineering   
3   E001  University of Visvesvaraya College of Engineering   
4   E001  University of Visvesvaraya College of Engineering   
5   E001  University of Visvesvaraya College of Engineering   
6   E002                S K S J T Institute of Engineering.   
7   E002                S K S J T Institute of Engineering.   
8   E002                S K S J T Institute of Engineering.   
9   E003                       B M S College of Engineering   
10  E003                       B M S College of Engineering   
11  E003                       B M S College of Engineering   
12  E003                       B M S College of Engineering   
13  E004               Dr. Ambedkar Institute Of Technology   
14  E004               Dr. Ambedkar Institute Of Technology   
15  E004               Dr. Ambedkar Institute Of Technology   
16  E004               Dr. Ambedkar Institute Of Technology   
17  E004               Dr. Ambedkar Institute Of Technology   
18  E005                       R. V. College of Engineering   
19  E005                       R. V. College of Engineering   
20  E005                       R. V. College of Engineering   
21  E005                       R. V. College of Engineering   
22  E005                       R. V. College of Engineering   
23  E006                M S Ramaiah Institute of Technology   
24  E006                M S Ramaiah Institute of Technology   
25  E006                M S Ramaiah Institute of Technology   
26  E006                M S Ramaiah Institute of Technology   
27  E006                M S Ramaiah Institute of Technology   
28  E006                M S Ramaiah Institute of Technology   
29  E007             Dayananda Sagar College of Engineering   
30  E007             Dayananda Sagar College of Engineering   
31  E007             Dayananda Sagar College of Engineering   
32  E007             Dayananda Sagar College of Engineering   
33  E007             Dayananda Sagar College of Engineering   
34  E007             Dayananda Sagar College of Engineering   
35  E007             Dayananda Sagar College of Engineering   

                        Branch  Min_Range  
0   AI Artificial Intelligence        160  
1                     CE Civil         80  
2                 CS Computers        150  
3               EC Electronics        130  
4                EE Electrical        100  
5                ME Mechanical        105  
6                     CE Civil         80  
7                 CS Computers        150  
8               EC Electronics        130  
9                     CE Civil         80  
10              EC Electronics        130  
11               EE Electrical        100  
12               ME Mechanical         95  
13                    CE Civil        100  
14                CS Computers        165  
15              EC Electronics        135  
16               EE Electrical        105  
17               ME Mechanical        110  
18  AI Artificial Intelligence        165  
19                    CE Civil        100  
20              EC Electronics        135  
21               EE Electrical        115  
22               ME Mechanical        100  
23  AI Artificial Intelligence        175  
24                    CE Civil        105  
25                CS Computers        150  
26              EC Electronics        120  
27               EE Electrical        115  
28               ME Mechanical         95  
29  AI Artificial Intelligence        160  
30                    CE Civil        115  
31                CS Computers        165  
32              EC Electronics        117  
33               EE Electrical        130  
34               ME Mechanical        140  
35          RI Robotics and AI        175

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df_co["Branch"]=encoder.fit_transform(df_co["Branch"])
df_co["ID"]=encoder.fit_transform(df_co["ID"])


In [7]:
df_co

ID                                           Colleges  Branch  Min_Range
0    0  University of Visvesvaraya College of Engineering       0        160
1    0  University of Visvesvaraya College of Engineering       1         80
2    0  University of Visvesvaraya College of Engineering       2        150
3    0  University of Visvesvaraya College of Engineering       3        130
4    0  University of Visvesvaraya College of Engineering       4        100
5    0  University of Visvesvaraya College of Engineering       5        105
6    1                S K S J T Institute of Engineering.       1         80
7    1                S K S J T Institute of Engineering.       2        150
8    1                S K S J T Institute of Engineering.       3        130
9    2                       B M S College of Engineering       1         80
10   2                       B M S College of Engineering       3        130
11   2                       B M S College of Engineering       4        100
12   2                       B M S College of Engineering       5         95
13   3               Dr. Ambedkar Institute Of Technology       1        100
14   3               Dr. Ambedkar Institute Of Technology       2        165
15   3               Dr. Ambedkar Institute Of Technology       3        135
16   3               Dr. Ambedkar Institute Of Technology       4        105
17   3               Dr. Ambedkar Institute Of Technology       5        110
18   4                       R. V. College of Engineering       0        165
19   4                       R. V. College of Engineering       1        100
20   4                       R. V. College of Engineering       3        135
21   4                       R. V. College of Engineering       4        115
22   4                       R. V. College of Engineering       5        100
23   5                M S Ramaiah Institute of Technology       0        175
24   5                M S Ramaiah Institute of Technology       1        105
25   5                M S Ramaiah Institute of Technology       2        150
26   5                M S Ramaiah Institute of Technology       3        120
27   5                M S Ramaiah Institute of Technology       4        115
28   5                M S Ramaiah Institute of Technology       5         95
29   6             Dayananda Sagar College of Engineering       0        160
30   6             Dayananda Sagar College of Engineering       1        115
31   6             Dayananda Sagar College of Engineering       2        165
32   6             Dayananda Sagar College of Engineering       3        117
33   6             Dayananda Sagar College of Engineering       4        130
34   6             Dayananda Sagar College of Engineering       5        140
35   6             Dayananda Sagar College of Engineering       6        175

In [10]:
x=df_co[['Branch','Min_Range']]
y=df_co['ID']

In [16]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()


In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
x_train.shape,x_test.shape

((28, 2), (8, 2))

In [17]:
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [18]:
y_predict=rfc.predict(x_test)

In [19]:
from sklearn.metrics import classification_report,accuracy_score
accuracy_score(y_predict,y_test)

0.125

In [21]:
print(classification_report(y_predict,y_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         3
           6       0.33      0.50      0.40         2

    accuracy                           0.12         8
   macro avg       0.06      0.08      0.07         8
weighted avg       0.08      0.12      0.10         8



In [28]:
rfc.predict([[0,150]])

array([0])

In [33]:
from sklearn.linear_model import LogisticRegression
log_ref=LogisticRegression()
log_ref.fit(x,y)

LogisticRegression()

In [35]:
log_ref.predict([[0,150]])

array([5])

In [36]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x,y)

DecisionTreeClassifier()

In [39]:
dtc.predict([[0,178]])

array([5])